### GET Insert example data
GET http://localhost:8080/insertSampleData

### GET Leaderboard of {game} minecraft and {category} kategorie

GET http://localhost:8080/rest/api/games/minecraft/any_percent/leaderboard

### GET All Games

GET http://localhost:8080/rest/api/games/all

### GET All categories of a game

GET http://localhost:8080/rest/api/games/minecraft/categories