/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package de.haw.se2.praktikum.speedrun.se2_speedrun.openapitools.api;

import de.haw.se2.praktikum.speedrun.se2_speedrun.openapitools.model.Category;
import de.haw.se2.praktikum.speedrun.se2_speedrun.openapitools.model.GameDto;
import de.haw.se2.praktikum.speedrun.se2_speedrun.openapitools.model.RunDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Optional;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-05-12T11:35:57.825139837Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
@Validated
@Tag(name = "games", description = "All about the games")
public interface GamesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /rest/api/games/all : Get all available games.
     * Get all available games.
     *
     * @return Returns all available games. (status code 200)
     */
    @Operation(
        operationId = "restApiGamesAllGet",
        summary = "Get all available games.",
        description = "Get all available games.",
        tags = { "games" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Returns all available games.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = GameDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rest/api/games/all",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<GameDto>> restApiGamesAllGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"imageUrl\" : \"imageUrl\", \"name\" : \"minecraft\", \"slug\" : \"slug\" }, { \"imageUrl\" : \"imageUrl\", \"name\" : \"minecraft\", \"slug\" : \"slug\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /rest/api/games/{gameSlug}/categories : Get available categories by game.
     * Get available categories by game.
     *
     * @param gameSlug  (required)
     * @return Returns all available categories for the given game. (status code 200)
     *         or Returned if the game were not found. (status code 404)
     */
    @Operation(
        operationId = "restApiGamesGameSlugCategoriesGet",
        summary = "Get available categories by game.",
        description = "Get available categories by game.",
        tags = { "games" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Returns all available categories for the given game.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Category.class)))
            }),
            @ApiResponse(responseCode = "404", description = "Returned if the game were not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rest/api/games/{gameSlug}/categories",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Category>> restApiGamesGameSlugCategoriesGet(
        @Parameter(name = "gameSlug", description = "", required = true, in = ParameterIn.PATH) @PathVariable("gameSlug") String gameSlug
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : \"ANY_PERCENT\", \"label\" : \"Any %\" }, { \"id\" : \"ANY_PERCENT\", \"label\" : \"Any %\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /rest/api/games/{gameSlug}/{categoryId}/leaderboard : Get leaderboard by game and category.
     * Get leaderboard by game and category.
     *
     * @param gameSlug the game of the leaderboard (required)
     * @param categoryId the category of the leaderboard (required)
     * @return Returns a list of runs that are representing the leaderboard. (status code 200)
     *         or Returned if the game or category were not found. (status code 404)
     */
    @Operation(
        operationId = "restApiGamesGameSlugCategoryIdLeaderboardGet",
        summary = "Get leaderboard by game and category.",
        description = "Get leaderboard by game and category.",
        tags = { "games" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Returns a list of runs that are representing the leaderboard.", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = RunDto.class)))
            }),
            @ApiResponse(responseCode = "404", description = "Returned if the game or category were not found.")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/rest/api/games/{gameSlug}/{categoryId}/leaderboard",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<RunDto>> restApiGamesGameSlugCategoryIdLeaderboardGet(
        @Parameter(name = "gameSlug", description = "the game of the leaderboard", required = true, in = ParameterIn.PATH) @PathVariable("gameSlug") String gameSlug,
        @Parameter(name = "categoryId", description = "the category of the leaderboard", required = true, in = ParameterIn.PATH) @PathVariable("categoryId") String categoryId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"speedrunner\" : \"speedrunner\", \"runtime\" : { \"milliseconds\" : 5, \"hours\" : 0, \"seconds\" : 1, \"minutes\" : 6 } }, { \"date\" : \"2000-01-23T04:56:07.000+00:00\", \"speedrunner\" : \"speedrunner\", \"runtime\" : { \"milliseconds\" : 5, \"hours\" : 0, \"seconds\" : 1, \"minutes\" : 6 } } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
